[DNCR-92] Attached company to users
tlegutko/dncr pull request #24
Opened 2016-10-02 12:05 UTC by szimin18

2016-10-02 12:52 UTC, Tifts commented on app/Models/Company.php
> -  protected $dates = [
Why was this removed?

2016-10-02 12:52 UTC, Tifts commented on app/Models/Traits/UserTypeRelated.php
> +trait UserTypeRelated
This class is crazy to me, I need an explanation.

2016-10-02 12:52 UTC, Tifts commented on app/Models/User.php
> +  const TYPE_USER = 'user';
For me this is confusing. An "instructor" should be a type of "user" - every entity ever using any part of our app is an "user". And it might be different types of users: "instructor", "attendee", "administrator", but "user" should NOT, in my opinion, be a type of user.

2016-10-02 12:52 UTC, Tifts commented on database/factories/ModelFactory.php
> -/*
All changes in this class - what are they for?

2016-10-02 12:52 UTC, Tifts commented on database/migrations/2014_10_12_000000_create_users_table.php
> +        $table->foreign('company_id')->references('id')->on('companies')->onDelete('cascade');
We most definitely do not want deleting a company delete all users ever registered in this company - 'cascade' is a wrong onDelete action here.

2016-10-02 12:52 UTC, Tifts commented on database/migrations/2014_10_12_000000_create_users_table.php
> +        $table->string('type');
Type is just a string? How do we bind it to that enum class I've seen before?

2016-10-07 10:26 UTC, megawebmaster commented on database/migrations/2014_10_12_000000_create_users_table.php
> +        $table->foreign('company_id')->references('id')->on('companies')->onDelete('cascade');
Well, we do. Because each user is tightly coupled to the company.

2016-10-07 10:30 UTC, megawebmaster commented on app/Models/Traits/UserTypeRelated.php
> +trait UserTypeRelated
https://www.youtube.com/watch?v=0p_1QSUsbsM ;)

As for more explanation: http://www.archybold.com/blog/post/booting-eloquent-model-traits

2016-10-07 10:31 UTC, megawebmaster commented on database/factories/ModelFactory.php
> -/*
Seems to me like code reformat + new `Company` model generator. See: https://laravel.com/docs/5.2/testing#model-factories

2016-10-07 10:32 UTC, megawebmaster commented on database/migrations/2014_09_10_112933_create_companies_table.php
> +        $table->timestamps();
As I said to @tlegutko - this was intentional to ensure proper timestamp creation on database side.

2016-10-10 17:00 UTC, Tifts commented on app/Models/Traits/UserTypeRelated.php
> +trait UserTypeRelated
Ok

2016-10-10 17:00 UTC, Tifts commented on database/factories/ModelFactory.php
> -/*
Ok.

2016-10-10 17:00 UTC, Tifts commented on database/migrations/2014_10_12_000000_create_users_table.php
> +        $table->foreign('company_id')->references('id')->on('companies')->onDelete('cascade');
Ok, I was confused with this name.

2016-10-26 06:55 UTC, megawebmaster requested changes

2016-10-26 06:55 UTC, megawebmaster commented on app/Models/Traits/CompanyRelated.php
> +      $model->company_id = JWTAuth::parseToken()->authenticate()->company->id;
Did you try to acquire company id outside of these functions? Will this work?

2016-10-26 06:55 UTC, megawebmaster commented on app/Models/Traits/CompanyRelated.php
> +    static::addGlobalScope(new class implements Scope
Could you extract this class as you have done in `UserTypeRelated`?

2016-10-26 06:55 UTC, megawebmaster commented on app/Models/Traits/UserTypeRelated.php
> +    static::creating(function($user) use ($type)
In `CompanyRelated` you have statically typed `Model` class as `$user` - wouldn't it work here as well?

2016-10-26 06:55 UTC, megawebmaster commented on app/Models/User.php
> +    'type',
I thought `type` is not fillable - it's filled by ourselves based on model we are using.

2016-10-26 06:55 UTC, megawebmaster commented on database/migrations/2014_09_10_112933_create_companies_table.php
> +        $table->timestamp('updated_at')->default(DB::raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
By default `updated_at` should be `null` - as the model is not yet updated.

2016-10-26 06:55 UTC, megawebmaster commented on database/migrations/2014_10_12_100000_create_password_resets_table.php
> +        $table->timestamp('updated_at')->default(DB::raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
We don't need `updated_at` here ;)

2016-11-02 12:58 UTC, szimin18 commented on app/Models/Traits/CompanyRelated.php
> +    static::addGlobalScope(new class implements Scope
done

2016-11-02 13:08 UTC, szimin18 commented on app/Models/Traits/CompanyRelated.php
> +      $model->company_id = JWTAuth::parseToken()->authenticate()->company->id;
I did not. Why should I try it? And why should it not work?

2016-11-02 13:28 UTC, szimin18 commented on app/Models/Traits/UserTypeRelated.php
> +    static::creating(function($user) use ($type)
Hmm.. I'm not sure what you mean. A user instance passed to this function is the instance which is currently being created. CompanyRelated does not contain any static field containing user. It, howver, obtains a user instance in a static context. I can't find connection between them.

2016-11-02 13:29 UTC, szimin18 commented on app/Models/User.php
> +    'type',
wright

2016-11-02 14:47 UTC, szimin18 commented on database/migrations/2014_09_10_112933_create_companies_table.php
> +        $table->timestamp('updated_at')->default(DB::raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
I would say it's a pholosophical question: "Should we regard creation as a modification". I changed it, but I don't see a difference.

2016-11-02 14:58 UTC, szimin18 commented on database/migrations/2014_10_12_100000_create_password_resets_table.php
> +        $table->timestamp('updated_at')->default(DB::raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
Done

2016-11-05 16:58 UTC, megawebmaster submitted a review, later dismissed

2016-11-05 16:58 UTC, megawebmaster commented on app/Models/Traits/UserTypeRelated.php
> +    static::creating(function($user) use ($type)
You seem not to understand: "statically typed" which means static typing or adding required type of parameter. I want this to be `function(User $user){ ... }`.

2016-11-11 18:13 UTC, tlegutko commented on app/Models/Traits/CompanyRelated.php
> +      static::$user;
why do we need `static::$user`?

 In DNCR-105 (adding instructors to course times) I'm using this branch and when I added `CompanyRelated` trait to `Course`, then fetching courses worked out of the box (adminY from Company 2 couldn't see Company 1's courses, nice!), but this `creating` method exploded, as `Course` does not have `user` property. What's interesting, when I deleted this line, both course creation and instructor creation works.

If it's somehow needed - how can we make it work for courses too?

2016-11-21 18:24 UTC, tlegutko commented on app/Models/Traits/CompanyRelated.php
> +      static::$user;
ping, delete it pls. and merge develop and let's have it finished

2016-12-12 16:56 UTC, tlegutko approved these changes

2016-12-12 16:57 UTC, merged