[Dncr-104] Course updates view.
tlegutko/dncr pull request #27
Opened 2016-10-09 20:42 UTC by tlegutko

Things to take notice of:
1. Now that save button is separated from the rest of course form by `<router-outlet>` front-end form validation doesn't work and there's only backend validation.
2. Title looks bad on mobile. I looked how you did mobile look for `title.component` for attendee list, but I decided it'd take me too long to fine-tune it in my case and left it. It That's not our priority for now and I'd happily do that sometime in the future in separate task.
3. Currently the back-end behaviour on edit request is to just create new course with provided data. I left proper updating for another task (https://trello.com/c/0FtcTLtX), because:
   - current flat structure of course-creation/edit request won't work, we need `ids` of all `course_times` and `course_events`, it'll be done here https://trello.com/c/JtGMgJvu
   - there's some additional logic on front-end calendar to handle it, it'll fit nicely as separate task
   - edits can have multiple meanings - do we want to alter all events? only following? only this one instance? there should be extra modal with additional strategies, like on google calc. and well, I'd rather not thing about deleting terms and all consequences for dependant models.
4. Currently clicking on any event in the series displays only the first `course_time` of this course and for this task it's intended -> I'll take a look at it once we have multiple course_times supported.
5. `CoursesService` is now even more busy to make components interact.. But I don't see a better way for now..
6. when editing course, the 'go back' and 'save button' are minimally misaligned (in relation to input field), I couldn't figure out how to fix them, maybe you'll have an idea.

2016-10-11 08:55 UTC, megawebmaster requested changes

2016-10-11 08:55 UTC, megawebmaster commented on frontend/src/app/manager/courses/course-title/course-title.component.html
> +  <button *ngIf="isEditIconVisible" type="button" class="btn btn-sm btn-secondary" (click)="toggleEditing()">
Rather `*ngIf="isCourseSaved()"`. Of course update code alignment as well I propose you take out `button` from `span` so you can align them properly.

2016-10-11 08:55 UTC, megawebmaster commented on frontend/src/app/manager/courses/course-title/course-title.component.html
> +  <span *ngIf="isEditing" [class.editing]="isEditing">
Replace `[class.editing]="isEditing"` with `class="editing"` - we completely remove this DOM node when if expression is false.

2016-10-11 08:55 UTC, megawebmaster commented on frontend/src/app/manager/courses/course-title/course-title.component.html
> +    <div class="col-xs-1 p-x-0">
Why so complicated? Move the button inside the `form-field` and align there - should work nicely ;) This would also simplify those `[class.col-xs-8]` thing - you will always get `col-xs-9` there.

2016-10-11 08:55 UTC, megawebmaster commented on frontend/src/app/manager/courses/course-title/course-title.component.html
> +      <button *ngIf="isEditIconVisible" type="button" class="btn btn-block btn-secondary" (click)="toggleEditing()">
It's not `toggleEditing()` - it should be `cancelEdit()`

2016-10-11 08:55 UTC, megawebmaster commented on frontend/src/app/manager/courses/course-title/course-title.component.ts
> +export class CreateCourseTitleComponent implements OnInit {
It's not `CreateCourseTitleComponent` anymore, is it?

2016-10-11 08:55 UTC, megawebmaster commented on frontend/src/app/manager/courses/course-title/course-title.component.ts
> +    let nonEditableRoutes = ['actions', 'attendees'];
I'd rather see whitelist here instead of blacklist. You could use `ActivatedRoute` to get nice methods for validation (take a look at `routerLinkActive` Angular2 directive - this should point you in the right direction).

2016-10-11 08:55 UTC, megawebmaster commented on frontend/src/app/manager/courses/edit/edit-course.component.html
> +
Empty file? :D

2016-10-16 12:51 UTC, megawebmaster commented on frontend/src/app/course/course.model.ts
> +// export class CreateCourseRequest {
Hmmm.

2016-10-16 12:51 UTC, megawebmaster commented on frontend/src/app/course/course.model.ts
> +  timeFormat = 'HH:mm:ss';
Drop seconds.

2016-11-06 11:57 UTC, megawebmaster requested changes
I'm finishing this task, so don't worry about comments - they are for me to remember where to update :)

2016-11-06 11:57 UTC, megawebmaster commented on app/Http/Controllers/CoursesController.php
> +    $course = Course::with('times.events')->findOrFail($id);
Why do you need times and events here?

2016-11-06 11:57 UTC, megawebmaster commented on app/Http/Requests/StoreCourseRequest.php
> +      'classesCount' => 'liczba zajęć 2',
?

2016-11-06 11:57 UTC, megawebmaster commented on frontend/src/app/course/course.model.ts
> +    if (this.times == null || this.times[0] == null) {
Why not simply initialize it? `times: CourseTime[] = [new CourseTime()];`?

2016-11-06 11:57 UTC, megawebmaster commented on frontend/src/app/course/course.model.ts
> +  static parseRequest(response: Response): Course {
I think this should be inside `CoursesService` as we don't care how we receive the data, we need them properly formatted. In case we change something in the format we could update `CoursesService` only, don't you think?

2016-11-06 11:57 UTC, megawebmaster commented on frontend/src/app/course/course.model.ts
> +    let c = new Course();
Maybe you could just return properly formatted value? Like this:

```
return {
  name: 'Salsa (początkujący)',
  price: 60,
  classesCount: 1,
  seatsCount: 1,
  ...
  times: [{
    startDate: '2016-10-26',
    ...
  }]
};
```

2016-11-06 11:57 UTC, megawebmaster commented on frontend/src/app/manager/courses/course-title/course-title.component.html
> +  <span *ngIf="isEditing()" class="editing">
Is this span required? Why not simple `<form-field *ngIf>`? You can style it as well, just like that:

```
h1 > form-field {
   // some styles here
}
```

2016-11-06 11:57 UTC, megawebmaster commented on frontend/src/app/manager/courses/course-title/course-title.component.ts
> +  @Output() save = new EventEmitter<boolean>();
Maybe `onSave` and `onClose`? :)

2016-11-06 21:02 UTC, tlegutko commented on frontend/src/app/course/course.model.ts
> +    if (this.times == null || this.times[0] == null) {
either way is good, in next task (99) I've removed this code anyway to handle more times.

2016-11-06 21:07 UTC, tlegutko commented on frontend/src/app/manager/courses/course-title/course-title.component.ts
> +  @Output() save = new EventEmitter<boolean>();
I think `save` and `close` is correct and consistent with Angular 2. when you add event to button you have `(click)`, not `(onClick)`. The handler method with prefix `on` makes sense, as it's used only in particular class.

even Angular 2 guys propose this convention in their style guide:
![image](https://cloud.githubusercontent.com/assets/10455138/20041697/602400fe-a46d-11e6-9d1a-7470caab1018.png)
https://angular.io/styleguide#!#05-16

2016-11-06 21:10 UTC, tlegutko commented on app/Http/Controllers/CoursesController.php
> +    $course = Course::with('times.events')->findOrFail($id);
We had that discussion once and I showed you version with and without `times.events` and without it they are simply not returned. And we need them in tasks branched from this one (99, 109) to present multiple course times of a course.

2016-11-06 21:13 UTC, tlegutko commented on frontend/src/app/course/course.model.ts
> +  static parseRequest(response: Response): Course {
well either way is fine for me, `CoursesService` seems to be a good place for it too :).

2016-11-13 10:32 UTC, megawebmaster commented on frontend/src/app/manager/courses/course-title/course-title.component.ts
> +  @Output() save = new EventEmitter<boolean>();
Well, I simply read it "backwards" - calling event emitters `on*` and methods `*` (i.e. `(onSave)="save()"`.

2016-11-13 14:04 UTC, megawebmaster commented on frontend/src/app/course/course.model.ts
> +  public clear() {
In case you ask - yes, this is required for all errors to be cleared properly. Without this we get old errors (i.e. when we select instructor but we still have other errors - we will see instructor required message).

2016-11-16 22:24 UTC, tlegutko reviewed
General comments:
1. ![image](https://cloud.githubusercontent.com/assets/10455138/20361457/ea3ed80a-ac37-11e6-83a4-fbdfe31bc0ac.png)
   nice! after spending so much time testing this form errors - it was satisfying to suddenly see nice notification confirmation of errors <3
2. generally super great job, they say the difficulty in programming is not in writing code - it's in removing not needed code ;).
3. You've got conflicts with develop, please remember to merge it
4. Minor stuff - when editing course title all form moves a little down (it doesn't happen in place). we agreed that fine-tuning UI is not our priority, so it's up to you if it needs to be fixed, I'm just noticing :)
5. I cannot approve / disapprove my own PR, but change requests are minor, so consider it approved as far as I'm concerned
6. **Important** I reviewed looking at your commits one by one and some of my comments are marked at `outdated`, please look at them as well :).

2016-11-16 22:24 UTC, tlegutko commented on app/Models/ModelCamelCaseConverter.php
> +      $result[$normalizer->denormalize($key)] = $value;
don't we need to denormalize values, as in `normalize`?

2016-11-16 22:24 UTC, tlegutko commented on frontend/src/app/course/course.model.ts
> +    return new Course({
u were right, now it looks much better :)

2016-11-16 22:24 UTC, tlegutko commented on frontend/src/app/course/course.model.ts
> +    if (fields) {
nice! I wish I knew this earlier, pretty clever optional constructor, I'm impressed :)

2016-11-16 22:24 UTC, tlegutko commented on frontend/src/app/course/course.model.ts
> +  public clear() {
~~I've been struggling with this myself (`cannot read property xxx of undefined... AGAIN, aaaargh!`) and I can see the intention, but don't we just need something like:~~
~~if (this.times == null) {
  this.times = [new CourseTimeErrors()];
}~~
~~because this undefined stuff happens anyway and what's tricky and error-prone are nested arrays. and it'd a lot of boilerplate here~~

EDIT: I've read your comment (good thinking that I'd ask :D) and you're right and I've seen this bug, but I forgot to address it. Your solution is right.

2016-11-16 22:24 UTC, tlegutko commented on frontend/src/app/course/courses.service.ts
> +        console.error('Error during calendarEvents()', e);
looks like debug info? all 4xx codes are logged anyway,, by zone, 500 is even logged with message in our `AuthHttp`, and if it was for us, e.json() would be better :). and if we want to log errors, I think we could just log them in once place (`AuthHttp`)

2016-11-16 22:24 UTC, tlegutko commented on frontend/src/app/manager/courses/course-title/course-title.component.ts
> +    this.save.emit((result: boolean) => {
sorry for next non-constructive comment, but this is simply brilliant! simple, in just one method and 1000x better in this event subscribers (`ManagerCoursesSingleComponent` / `CreateCourseComponent`). nice!

I think it'd be even better if `result` could be renamed to `successfulSave` / `saveSuccess` / `sucess`, but I'm so impressed that I don't mind if keep current name.

2016-11-16 22:24 UTC, tlegutko commented on frontend/src/app/manager/courses/edit/course-properties/course-properties.component.scss
> +  @include clearfix();
learning time - what does it do? I've refreshed the page with/without and didn't see the difference, then:
1) I've googled that clearfix is needed for handling floating stuff and I don't see where we have it
2) there is no `.form-group` top level class in `course-properties.component.html`, and I didn't find it with quick look at elements in chrome dev tools - is it even loaded?

edit: I've found interesting use-case here http://v4-alpha.getbootstrap.com/utilities/clearfix/ , but I still don't see that situation in `course-properties`, but I might be missing smth

2016-11-16 22:24 UTC, tlegutko commented on frontend/src/app/manager/courses/course-title/course-title.component.ts
> +    this.isNew = this.model.id === undefined;
I think you're generally right to leave title state even when route changes (clicking on `Akcje` or `Kursanci` can leave title in `editing` state and it's simpler and alright, good decision) but there's one more tricky use-case:
1. Create another course besides `Kurs 1`
2. Start editing `Kurs 1` title
3. Click on another course
4. The title is in editing state (little unexpected), but the name changes to correct one, so I guess it's ok
5. Cancel editing - BAM, title (and model) is set to `Kurs 1`. not nice!

Well I'm aware that I'm probably the only person ever to go through this use case, but it's still a bug. I don't see a quick fix without returning to condition after route change, but as it's super unlikely scenario you can just create low priority trello issue so it's fixed sometime in future.

2016-11-16 22:24 UTC, tlegutko commented on frontend/src/app/_commons/labelled-form-field/labelled-form-field.component.scss
> +  @include make-row();
little learning time, what happened? I've looked it up, but I still don't get it:
![image](https://cloud.githubusercontent.com/assets/10455138/20367575/6938d094-ac50-11e6-8c16-cf8fccd10a23.png)
I guess if we have `display: block`, then flex is not enabled and it just includes `@clearfix` mixin?
So is it so that about parent component would correctly span around children so it could be styled accordingly? I still don't get when `@clearfix` is needed and when not

when I commented it out labels got to the right side of input's (no idea why). 

and generally those label fields look way better than on develop, so nice work. I just tried to get some insight into how it happened

2016-11-16 22:24 UTC, tlegutko commented on frontend/src/app/_commons/labelled-form-field/labelled-form-field.component.ts
> +      <div class="form-group" [class.has-danger]="errors">
learning time :P, why was it better idea not to use form-field? error-displaying html looks the same, but I guess the devil's in styles? :)

2016-11-16 22:24 UTC, tlegutko commented on frontend/src/app/manager/courses/course-title/course-title.component.html
> +    <i class="fa fa-arrow-left" *ngIf="!isEditing"></i>
I think when creating course we also want `arrow-left` for consistency, as it "goes back" the same when editing course or looking at attendee list from reception (where we have arrows as well). I guess extra `if isNew` will easily do it. 

btw at first I was against those `arrow-left`, but then I noticed that they're quite an often seen pattern in mobile apps, thanks for convincing me earlier :).

2016-12-07 08:14 UTC, megawebmaster commented on frontend/src/app/_commons/labelled-form-field/labelled-form-field.component.scss
> +  @include make-row();
It's simpler - clearfix is required when we nest some containers using `float` - as it changes the way things are in the document flow. Clearing after it is required for items to "take" its place properly.

And `$enable-flex` is global variable that makes Bootstrap use flexbox instead of relying on floats ;)

2016-12-07 08:14 UTC, megawebmaster commented on frontend/src/app/_commons/labelled-form-field/labelled-form-field.component.ts
> +      <div class="form-group" [class.has-danger]="errors">
The problem was in... errors ;) As you can see there is the difference with it (proper column using).

2016-12-07 08:14 UTC, megawebmaster commented on frontend/src/app/course/course.model.ts
> +    if (fields) {
I wish I knew this earlier as well ;)

2016-12-07 08:14 UTC, megawebmaster commented on frontend/src/app/course/courses.service.ts
> +        console.error('Error during calendarEvents()', e);
I think I had some issues here and that's why I left it. I think we won't need to remove it right now as the development is still on going and we can use a kind of replacer to remove all `console` uses while building for production ;)

2016-12-07 08:14 UTC, megawebmaster commented on frontend/src/app/manager/courses/course-title/course-title.component.html
> +    <i class="fa fa-arrow-left" *ngIf="!isEditing"></i>
You mean when creating course to have an arrow instead of cross? I'm the opposite of that - as cross is used to close the view and cancel creating - I wanted to push more on cancelling than closing the view ;)

2016-12-07 08:14 UTC, megawebmaster commented on frontend/src/app/manager/courses/edit/course-properties/course-properties.component.scss
> +  @include clearfix();
Seems like a thing I left behind ;)

2016-12-07 08:16 UTC, megawebmaster approved these changes

2016-12-12 16:13 UTC, merged