[DNCR-35] Mail sending.
tlegutko/dncr pull request #36
Opened 2016-11-01 18:12 UTC by tlegutko

I started this PR for easier collaboration on this task.

2016-11-05 16:53 UTC, megawebmaster requested changes

2016-11-05 16:53 UTC, megawebmaster commented on .env.dev
> +MAIL_HOST=mail.dncr.pl
This shouldn't be here... This is why .env exists so .env.dev could contain developer values (which are not what real values are like!) and we need this password to be confidential, don't you think? Use:

```
MAIL_HOST=localhost
MAIL_PORT=25
MAIL_USERNAME=
MAIL_PASSWORD=
```

and Papercut for development.

2016-11-05 16:53 UTC, megawebmaster commented on app/Http/Controllers/MailController.php
> +  public function __construct()
No need for adding this middleware anymore.

2016-11-05 16:53 UTC, megawebmaster commented on database/seeds/AttendeesTableSeeder.php
> +                                     'email' => 'bartosz.rakoczy@gmail.com',
I'd rather remove this if I were you :D

2016-11-05 16:53 UTC, megawebmaster commented on routes/api.php
> +  Route::post('mail', 'MailController@send');
As this is mail for specific course - then why not `courses/{id}/send-message`? You will remove `course_id` from the request then and everything will look better ;)

2016-11-05 16:53 UTC, megawebmaster commented on frontend/src/app/manager/courses/single/actions/mail.service.ts
> +  public send(mail: Mail) {
After changing to `courses/{id}/send-message` you could rename it into `sendMessageForCourse(course: Course, mail: Mail)`

2016-11-05 16:53 UTC, megawebmaster commented on frontend/src/app/manager/courses/single/actions/mail.service.ts
> +import { AuthHttp } from 'angular2-jwt';
Use `AuthHttp` from `app/_commons/auth` - otherwise it won't work nicely.

2016-11-05 21:44 UTC, tlegutko commented on .env.dev
> +MAIL_HOST=mail.dncr.pl
by papercut you mean this? https://papercut.codeplex.com/
maybe https://laravel.com/docs/5.3/mail#mail-and-local-development just logging mails for development would be even more convenient?

2016-11-05 21:49 UTC, tlegutko commented on app/Http/Controllers/MailController.php
> +  public function __construct()
I'm responsible for this, I thought it was needed when I helped Bartek with some bugs. But as I learned from Amadeusz, `api` is automatically asigned because this call to this controller/method is defined in `api.php` file. Additional info from docs:
![image](https://cloud.githubusercontent.com/assets/10455138/20033809/1127012c-a3aa-11e6-8dbd-8ed146181e62.png)

https://laravel.com/docs/5.3/middleware#middleware-groups

2016-11-05 21:51 UTC, tlegutko commented on frontend/src/app/manager/courses/single/actions/mail.service.ts
> +import { AuthHttp } from 'angular2-jwt';
(merge develop first, then you'll have `AuthHttp` available).

2016-11-06 19:09 UTC, Tifts commented on database/seeds/AttendeesTableSeeder.php
> +                                     'email' => 'bartosz.rakoczy@gmail.com',
Yeah, you're right. :D

2016-11-13 09:46 UTC, megawebmaster requested changes
Please update to recent develop as well ;)

Did you verify if this works correcly? I suppose emails are being logged into `logs/laravel.log` file.

2016-11-13 09:46 UTC, megawebmaster commented on frontend/src/app/manager/courses/single/actions/actions.component.ts
> +    this.mailService.sendMessageForCourse(this.courseId, this.mail).subscribe(
Signatures won't match ;) I'd rather go for passing `Course` instead of course id ;)

2016-11-13 09:46 UTC, megawebmaster commented on frontend/src/app/manager/courses/single/actions/actions.component.ts
> +  private courseId;
Remember to add types ;)

2016-11-13 09:46 UTC, megawebmaster commented on routes/api.php
> +  Route::post('courses/{id}/send-message', 'MailController@send');
Please move this controller into `App\Http\Controllers\Courses` namespace (so it's relevant to courses only).

2016-12-07 08:01 UTC, megawebmaster approved these changes

2016-12-07 08:18 UTC, merged